-- Snapshot Product.name onto each order line.
--
-- Hand-written instead of autogenerated: Prisma cannot add a NOT NULL column to a
-- populated table without a literal default, and a default here would be a lie
-- (every existing row has a real name reachable through the FK).
--
-- OPERATIONAL PRECONDITION: expand, backfill and contract are collapsed into this
-- one migration, so it is NOT safe under a rolling deploy. Between the moment this
-- runs and the moment traffic moves to the new release, any still-serving instance
-- of the PREVIOUS release inserts order_items without product_name and gets a NOT
-- NULL violation (surfaces as a 500, not a domain error). The same applies to an
-- app-only rollback: order creation stays broken until the column is made nullable
-- by hand.
--
-- Apply it with no previous-release instance accepting writes. If that cannot be
-- guaranteed, split it across two releases instead: release 1 ships steps 1-2 with
-- the column nullable and the app already writing it, release 2 ships step 3.

-- 1. Expand: nullable, so existing rows survive the ALTER.
ALTER TABLE "order_items" ADD COLUMN "product_name" TEXT;

-- 2. Backfill: order_items.product_id is a NOT NULL FK to products.id, so this
--    join reaches every row and leaves no NULL behind.
UPDATE "order_items" AS oi
SET "product_name" = p."name"
FROM "products" AS p
WHERE p."id" = oi."product_id";

-- 3. Contract: fails loudly if step 2 missed anything.
ALTER TABLE "order_items" ALTER COLUMN "product_name" SET NOT NULL;
