export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  LOGOUT: 'LOGOUT',
  /** A revoked refresh token was re-presented; the whole rotation family was killed. */
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  USER_CREATED: 'USER_CREATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_BUSINESS_UNITS_CHANGED: 'USER_BUSINESS_UNITS_CHANGED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
  CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_REFUSED: 'PAYMENT_REFUSED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  /** Payment approved but the order could not be confirmed - needs manual reconciliation. */
  PAYMENT_RECONCILE_REQUIRED: 'PAYMENT_RECONCILE_REQUIRED',
  BUSINESS_UNIT_ACTIVATED: 'BUSINESS_UNIT_ACTIVATED',
  BUSINESS_UNIT_DEACTIVATED: 'BUSINESS_UNIT_DEACTIVATED',
  BUSINESS_UNIT_UPDATED: 'BUSINESS_UNIT_UPDATED',
  PRODUCT_ACTIVATED: 'PRODUCT_ACTIVATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  MENU_ITEM_ACTIVATED: 'MENU_ITEM_ACTIVATED',
  MENU_ITEM_DEACTIVATED: 'MENU_ITEM_DEACTIVATED',
  PROMOTION_ACTIVATED: 'PROMOTION_ACTIVATED',
  PROMOTION_DEACTIVATED: 'PROMOTION_DEACTIVATED',
  /** A deduction left a product at or below its minQuantity threshold. */
  STOCK_ALERT: 'STOCK_ALERT',
  /** Customer granted LGPD consent for the loyalty program. */
  LOYALTY_CONSENT_GIVEN: 'LOYALTY_CONSENT_GIVEN',
  /** Customer withdrew LGPD consent for the loyalty program. */
  LOYALTY_CONSENT_REVOKED: 'LOYALTY_CONSENT_REVOKED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
