-- Give every chat thread a title.
--
-- Hand-written instead of autogenerated for the same reason as
-- 20260723120000_add_order_item_product_name: Prisma cannot add a NOT NULL column to
-- a populated table without a literal default, and a literal default here would be a
-- lie for every existing thread that has a real opening message to derive from.
--
-- ROLLING-DEPLOY SAFETY: entrypoint.sh runs `prisma migrate deploy` at container boot,
-- so this migration ALWAYS runs while the previous release is still accepting writes.
-- That release's create() issues `data: { userId }` with no title, which a bare NOT
-- NULL would reject - every new thread would 500 on POST /api/ai/chat until the
-- cutover completed, and would stay broken through an app-level rollback.
--
-- Step 4 therefore pairs NOT NULL with a DEFAULT. The old release's insert falls back
-- to it and keeps working; the new release always supplies a real title, so the
-- default is only ever reached during the overlap window. DROP DEFAULT belongs in a
-- LATER release, once no instance that omits the column can still be running.
--
-- The default is not a lie about history the way it would be for the backfill: step 2
-- gives existing rows their real opening message, and step 3 covers the rest.

-- 1. Expand: nullable, so existing rows survive the ALTER.
ALTER TABLE "ai_conversations" ADD COLUMN "title" TEXT;

-- 2. Backfill from each thread's FIRST user turn, mirroring deriveConversationTitle:
--    collapse whitespace runs, trim, fall back when nothing is left, then cap at 80.
--
--    One deliberate difference from the application: no word-boundary cut. That
--    heuristic exists to make new titles read well and is not worth reimplementing in
--    SQL for historical rows - a hard cut at 77 plus an ellipsis is the same contract.
--
--    char_length and left() both count characters, not bytes, which is what keeps this
--    consistent with the code-point slicing the app does.
UPDATE "ai_conversations" AS c
SET "title" = CASE
      WHEN char_length(f."normalized") > 80 THEN left(f."normalized", 77) || '...'
      ELSE f."normalized"
    END
FROM (
  -- DISTINCT ON + ORDER BY picks the earliest user turn per thread. The id tie-break
  -- keeps the choice deterministic when two turns share a created_at.
  SELECT DISTINCT ON (m."conversation_id")
         m."conversation_id" AS conversation_id,
         COALESCE(
           NULLIF(btrim(regexp_replace(m."content", '\s+', ' ', 'g')), ''),
           'New conversation'
         ) AS "normalized"
  FROM "ai_conversation_messages" AS m
  WHERE m."role" = 'USER'
  ORDER BY m."conversation_id", m."created_at" ASC, m."id" ASC
) AS f
WHERE f.conversation_id = c."id";

-- 3. Threads that never got a user turn stored (a thread is created before the first
--    append, so a crash in between leaves one) have nothing to derive from.
UPDATE "ai_conversations" SET "title" = 'New conversation' WHERE "title" IS NULL;

-- 4. Contract: fails loudly if steps 2-3 missed anything. The DEFAULT is what keeps
--    the PREVIOUS release's title-less insert alive during the rolling-deploy overlap
--    described above; drop it in a later release, not here.
ALTER TABLE "ai_conversations"
  ALTER COLUMN "title" SET NOT NULL,
  ALTER COLUMN "title" SET DEFAULT 'New conversation';
